/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiLogsSubscriptionFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ChangeStreamService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "ClerkPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CreateAdminApiKeyFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "EventsTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MongoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OnItChefVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}